<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RestSuccess</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>18c5e0ee-42d3-4851-8264-4293616d9423</testSuiteGuid>
   <testCaseLink>
      <guid>f6fa94f6-c120-4435-9fe4-43a476f991f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/EmployeeTesting/RestApi</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8cdd1ca9-4c10-48e2-b30d-dc8bbdd98cd3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/employeeData (1)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c149d2c-9dc8-433a-9745-597fd682d8f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8cdd1ca9-4c10-48e2-b30d-dc8bbdd98cd3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>employeeName</value>
         <variableId>2fa44f8c-a706-469d-a13e-b767c9b4f4cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8cdd1ca9-4c10-48e2-b30d-dc8bbdd98cd3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>employeeSalary</value>
         <variableId>6778211a-777b-4cad-8f71-c464dcad2162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8cdd1ca9-4c10-48e2-b30d-dc8bbdd98cd3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>employeeAge</value>
         <variableId>adbb2636-3b17-4d9e-a2c3-6e8d7dca9da0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
