<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Create employee tests that are supposed to pass</description>
   <name>RestFail</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a063af01-f63f-4138-a385-b97a25c8f8ca</testSuiteGuid>
   <testCaseLink>
      <guid>0fe9586d-c261-44ad-b4b2-e728257c33ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/EmployeeTesting/RestApi</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cd963d74-d816-40b2-afd7-67c839303a5f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/badEmployeeData (1)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c149d2c-9dc8-433a-9745-597fd682d8f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fa44f8c-a706-469d-a13e-b767c9b4f4cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6778211a-777b-4cad-8f71-c464dcad2162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adbb2636-3b17-4d9e-a2c3-6e8d7dca9da0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
